import home from './home';
import homeAnimation from './home-animation';
import topbar from './topbar';
import navbar from './navbar';
import mobileMenu from './mobile-menu';
import homeSocialLinks from './home-social-links';
import services from './services';
import portfolio from './portfolio';
import toggleFullScreen from './toggleFullScreen';
import about from './about';

home();
homeAnimation();
topbar();
navbar();
mobileMenu();
homeSocialLinks();
services();
portfolio();
toggleFullScreen();
about();
