import home from './home';
import homeAnimation from './home-animation';
import topbar from './topbar';
import navbar from './navbar';
import mobileMenu from './mobile-menu';
import homeSocialLinks from './home-social-links';
import services from './services';
import portfolio from './portfolio';
import toggleFullScreen from './toggleFullScreen';
import about from './about';
import testimonials from './testimonials';
import faq from './faq';
import partners from './partners';
import contact from './contact';
import androidKeyboardFix from './android-keyboard-fix';

home();
homeAnimation();
topbar();
navbar();
mobileMenu();
homeSocialLinks();
services();
portfolio();
toggleFullScreen();
about();
testimonials();
faq();
partners();
contact();
androidKeyboardFix();
